### ISSUE TITLE
Playlist React project 

### ISSUE THREAD

**Issue by julianoiret** [julianoiret/playlist-react#1]
# Overview

We want to build a React project from scratch to improve our React skills.
This project is a single web page, which displays some playlists. Each playlists is a selection of our favorite musics and artists.
We can filter out playlists by category using dynamic nav with `buttons`. 

🍐 [@beyondthefruit](https://github.com/beyondthefruit)

# Design 

(coming soon)

# Structure

```
├── App.js
├── Header.js
├── Categories.js
├── PlaylistCards.js
├── Footer.js
├── data.js
├── index.js
├── index.css

```
# Tasks

- [ ] Draft the design
- [ ] Create React app
- [ ] Create our data file
- [ ] Create all the component files (see above)
- [ ] Styling (styled-component or SCSS?) 
- [ ] Add `favicon`, project name and description (tab)
- [ ] Create test file / follow testing strategy steps
- [ ] Host the project with Netifly 

# Testing strategy

- [ ] Unit tests using Jest and testing-library
- [ ] UI testing: manually test the page
- [ ] Testing on Firefox  
- [ ] Testing on Chrome
- [ ] Testing with different breakpoints (desktop - laptop - mobile)
